//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml;
using System.Xml.Serialization;

namespace ServiceReference2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.analitica.com.co/AZSign/WS", ConfigurationName="ServiceReference2.ServiciosAZSign_SOAP")]
    public interface ServiciosAZSign_SOAP
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:#Acuerdo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AplicativoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EventoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AcuerdoInfoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AcuerdoType))]
        System.Threading.Tasks.Task<ServiceReference2.AcuerdoResponse> AcuerdoAsync(ServiceReference2.AcuerdoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:#NewOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AplicativoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EventoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AcuerdoInfoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AcuerdoType))]
        System.Threading.Tasks.Task<ServiceReference2.SolicitarInfoAcuerdoResponse> SolicitarInfoAcuerdoAsync(ServiceReference2.SolicitarInfoAcuerdoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    [XmlRoot(Namespace = "http://www.analitica.com.co/AZSign/Esquemas", ElementName = "Acuerdo")]
    public partial class Acuerdo : AcuerdoType
    {
        [XmlNamespaceDeclarations]
        public XmlSerializerNamespaces xmlns = new XmlSerializerNamespaces(new[] {
            new XmlQualifiedName("azs", "http://www.analitica.com.co/AZSign/Esquemas")
        });
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoType
    {
        
        private AcuerdoTypeGrupo[] gruposPartcipantesField;
        
        private AcuerdoTypeCopia[] copiasField;
        
        private string mensajeField;
        
        private AcuerdoTypeDocumento[] documentosField;
        
        private AcuerdoTypeRemitente remitenteField;
        
        private string cuentaField;
        
        private string grupoField;
        
        private string aplicativoField;
        
        private string nombreField;
        
        private AcuerdoTypeTipoFirma tipoFirmaField;
        
        private AcuerdoTypeEstado estadoField;
        
        private string refWebHookField;
        
        private string urlPostFirmaField;
        
        private AcuerdoTypeSegundoFacAut segundoFacAutField;
        
        private bool segundoFacAutFieldSpecified;
        
        private string estamparCronologicamenteField;
        
        private System.DateTime vencimientoField;
        
        private bool vencimientoFieldSpecified;
        
        private string notificarRemitenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AcuerdoTypeGrupo[] GruposPartcipantes
        {
            get
            {
                return this.gruposPartcipantesField;
            }
            set
            {
                this.gruposPartcipantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Copia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AcuerdoTypeCopia[] Copias
        {
            get
            {
                return this.copiasField;
            }
            set
            {
                this.copiasField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Documento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AcuerdoTypeDocumento[] Documentos
        {
            get
            {
                return this.documentosField;
            }
            set
            {
                this.documentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public AcuerdoTypeRemitente Remitente
        {
            get
            {
                return this.remitenteField;
            }
            set
            {
                this.remitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cuenta
        {
            get
            {
                return this.cuentaField;
            }
            set
            {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Grupo
        {
            get
            {
                return this.grupoField;
            }
            set
            {
                this.grupoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Aplicativo
        {
            get
            {
                return this.aplicativoField;
            }
            set
            {
                this.aplicativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AcuerdoTypeTipoFirma TipoFirma
        {
            get
            {
                return this.tipoFirmaField;
            }
            set
            {
                this.tipoFirmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AcuerdoTypeEstado Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefWebHook
        {
            get
            {
                return this.refWebHookField;
            }
            set
            {
                this.refWebHookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UrlPostFirma
        {
            get
            {
                return this.urlPostFirmaField;
            }
            set
            {
                this.urlPostFirmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AcuerdoTypeSegundoFacAut SegundoFacAut
        {
            get
            {
                return this.segundoFacAutField;
            }
            set
            {
                this.segundoFacAutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SegundoFacAutSpecified
        {
            get
            {
                return this.segundoFacAutFieldSpecified;
            }
            set
            {
                this.segundoFacAutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EstamparCronologicamente
        {
            get
            {
                return this.estamparCronologicamenteField;
            }
            set
            {
                this.estamparCronologicamenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Vencimiento
        {
            get
            {
                return this.vencimientoField;
            }
            set
            {
                this.vencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VencimientoSpecified
        {
            get
            {
                return this.vencimientoFieldSpecified;
            }
            set
            {
                this.vencimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NotificarRemitente
        {
            get
            {
                return this.notificarRemitenteField;
            }
            set
            {
                this.notificarRemitenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoTypeGrupo
    {
        
        private AcuerdoTypeGrupoParticipante[] participanteField;
        
        private uint ordenField;
        
        private AcuerdoTypeGrupoRol rolField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Participante", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AcuerdoTypeGrupoParticipante[] Participante
        {
            get
            {
                return this.participanteField;
            }
            set
            {
                this.participanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AcuerdoTypeGrupoRol Rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoTypeGrupoParticipante
    {
        
        private string emailField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string tipoIdentificacionField;
        
        private string numeroDocumentoField;
        
        private string celularField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoIdentificacion
        {
            get
            {
                return this.tipoIdentificacionField;
            }
            set
            {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Celular
        {
            get
            {
                return this.celularField;
            }
            set
            {
                this.celularField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AplicativoType
    {
        
        private string idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class EventoType
    {
        
        private string idField;
        
        private string nombreField;
        
        private System.DateTime fechaHoraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime FechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class GrupoType
    {
        
        private string idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
   // [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace ="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class CuentaType
    {
        
        private string idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoType
    {
        
        private AcuerdoInfoTypeEstado estadoField;
        
        private CuentaType cuentaField;
        
        private GrupoType grupoRegistroField;
        
        private AcuerdoInfoTypeOrigen origenField;
        
        private AcuerdoInfoTypeGrupo[] gruposPartcipantesField;
        
        private string mensajeField;
        
        private object observacionnesField;
        
        private AcuerdoInfoTypeDocumento[] documentosField;
        
        private AcuerdoInfoTypeCopias copiasField;
        
        private string idField;
        
        private string nombreField;
        
        private string refWebHookField;
        
        private string urlPostFirmaField;
        
        private System.DateTime? fechaRecepcionField;
        
        private bool fechaRecepcionFieldSpecified;
        
        private string fechaVencimientoField;
        
        private System.DateTime? fechaFinalizacionField;
        
        private bool fechaFinalizacionFieldSpecified;
        
        private System.DateTime? fechaFirmaDigitalField;
        
        private bool fechaFirmaDigitalFieldSpecified;
        
        private AcuerdoInfoTypeSegundoFacAut? segundoFacAutField;
        
        private bool segundoFacAutFieldSpecified;
        
        private bool estampadoCronologicoField;
        
        private bool estampadoCronologicoFieldSpecified;
        
        private bool? notificarRemitenteField;
        
        private bool notificarRemitenteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AcuerdoInfoTypeEstado Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public CuentaType Cuenta
        {
            get
            {
                return this.cuentaField;
            }
            set
            {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order =2)]
        public GrupoType GrupoRegistro
        {
            get
            {
                return this.grupoRegistroField;
            }
            set
            {
                this.grupoRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public AcuerdoInfoTypeOrigen Origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grupo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AcuerdoInfoTypeGrupo[] GruposPartcipantes
        {
            get
            {
                return this.gruposPartcipantesField;
            }
            set
            {
                this.gruposPartcipantesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public object Observacionnes
        {
            get
            {
                return this.observacionnesField;
            }
            set
            {
                this.observacionnesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Documento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AcuerdoInfoTypeDocumento[] Documentos
        {
            get
            {
                return this.documentosField;
            }
            set
            {
                this.documentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public AcuerdoInfoTypeCopias Copias
        {
            get
            {
                return this.copiasField;
            }
            set
            {
                this.copiasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefWebHook
        {
            get
            {
                return this.refWebHookField;
            }
            set
            {
                this.refWebHookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UrlPostFirma
        {
            get
            {
                return this.urlPostFirmaField;
            }
            set
            {
                this.urlPostFirmaField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("FechaRecepcion")]
        public string FechaRecepcionString
        {
            //get
            //{
            //    return fechaRecepcionField.ToString("yyyy-MM-ddTHH:mm:ss");
            //}
            //set { }

            get
            {
                return this.fechaRecepcionField.HasValue ? XmlConvert.ToString(fechaRecepcionField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaRecepcionField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)System.DateTime.Now;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore]
        public System.DateTime? FechaRecepcion
        {
            get
            {
                return this.fechaRecepcionField;
            }
            set
            {
                this.fechaRecepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaRecepcionSpecified
        {
            get
            {
                return this.fechaRecepcionFieldSpecified;
            }
            set
            {
                this.fechaRecepcionFieldSpecified = value;
            }
        }

        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaVencimiento
        {
            get
            {
                return this.fechaVencimientoField;
            }
            set
            {
                this.fechaVencimientoField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("FechaFinalizacion")]
        public string FechaFinalizacionString
        {
            get
            {
                return this.fechaFinalizacionField.HasValue ? XmlConvert.ToString(fechaFinalizacionField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaFinalizacionField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTime? FechaFinalizacion
        {
            get
            {
                return this.fechaFinalizacionField;
            }
            set
            {
                this.fechaFinalizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaFinalizacionSpecified
        {
            get
            {
                return this.fechaFinalizacionFieldSpecified;
            }
            set
            {
                this.fechaFinalizacionFieldSpecified = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("FechaFirmaDigital")]
        public string FechaFirmaDigitalString
        {
            get
            {
                return this.fechaFirmaDigitalField.HasValue ? XmlConvert.ToString(fechaFirmaDigitalField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaFirmaDigitalField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.DateTime? FechaFirmaDigital
        {
            get
            {
                return this.fechaFirmaDigitalField;
            }
            set
            {
                this.fechaFirmaDigitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaFirmaDigitalSpecified
        {
            get
            {
                return this.fechaFirmaDigitalFieldSpecified;
            }
            set
            {
                this.fechaFirmaDigitalFieldSpecified = value;
            }
        }
        
        //public AcuerdoInfoTypeSegundoFacAut funcT(object value)
        //{
        //    var e = value;
        //    if (Enum.IsDefined(typeof(AcuerdoInfoTypeSegundoFacAut), value))
        //        return (AcuerdoInfoTypeSegundoFacAut)value;
                    
        //     return AcuerdoInfoTypeSegundoFacAut.Null;
        //}

        [System.Xml.Serialization.XmlAttributeAttribute("SegundoFacAut")]
        public string SegundoFacAutString
        {
            get
            {
                return this.segundoFacAutField.ToString();
            }
            set
            {
                this.segundoFacAutField = (AcuerdoInfoTypeSegundoFacAut?)(Enum.IsDefined(typeof(AcuerdoInfoTypeSegundoFacAut), value)? Enum.Parse(typeof(AcuerdoInfoTypeSegundoFacAut),value): null);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public AcuerdoInfoTypeSegundoFacAut? SegundoFacAut
        {
            get
            {
                return this.segundoFacAutField;
            }
            set
            {
                this.segundoFacAutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SegundoFacAutSpecified
        {
            get
            {
                return this.segundoFacAutFieldSpecified;
            }
            set
            {
                this.segundoFacAutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EstampadoCronologico
        {
            get
            {
                return this.estampadoCronologicoField;
            }
            set
            {
                this.estampadoCronologicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstampadoCronologicoSpecified
        {
            get
            {
                return this.estampadoCronologicoFieldSpecified;
            }
            set
            {
                this.estampadoCronologicoFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("NotificarRemitente")]
        public string NotificarRemitenteString
        {
            get
            {
                return this.notificarRemitenteField.ToString();
            }
            set
            {
                this.notificarRemitenteField = String.IsNullOrWhiteSpace(value)? null : Boolean.Parse(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool? NotificarRemitente
        {
            get
            {
                return this.notificarRemitenteField;
            }
            set
            {
                this.notificarRemitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotificarRemitenteSpecified
        {
            get
            {
                return this.notificarRemitenteFieldSpecified;
            }
            set
            {
                this.notificarRemitenteFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoTypeEstado
    {
        
        private string idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoTypeOrigen
    {
        
        private string tipoField;
        
        private string idField;
        
        private string referenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoTypeGrupo
    {
        
        private AcuerdoInfoTypeGrupoParticipante[] participanteField;
        
        private string idField;
        
        private uint ordenField;
        
        private AcuerdoInfoTypeGrupoRol rolField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Participante", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AcuerdoInfoTypeGrupoParticipante[] Participante
        {
            get
            {
                return this.participanteField;
            }
            set
            {
                this.participanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AcuerdoInfoTypeGrupoRol Rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoTypeGrupoParticipante
    {
        
        private AcuerdoInfoTypeGrupoParticipanteEstado estadoField;
        
        private object observacionesField;
        
        private string idField;
        
        private string emailField;
        
        private string nombreField;

        private string apellidoField;


        private string celularField;
        
        private System.DateTime? fechaEnvioParaFirmaField;
        
        private bool fechaEnvioParaFirmaFieldSpecified;
        
        private System.DateTime? fechaLecturaParaFirmaField;
        
        private bool fechaLecturaParaFirmaFieldSpecified;
        
        private string ipLecturaParaFirmaField;
        
        private System.DateTime? fechaRespuestaField;
        
        private bool fechaRespuestaFieldSpecified;
        
        private string ipRespuestaField;
        
        private System.DateTime? fechaEnvioDocumentoFirmadoField;
        
        private bool fechaEnvioDocumentoFirmadoFieldSpecified;
        
        private System.DateTime? fechaDescargaDocumentoFirmadoField;
        
        private bool fechaDescargaDocumentoFirmadoFieldSpecified;
        
        private string ipDescargaDocumentoFirmadoField;
        
        private string nombreEnFirmaField;
        
        private string identificacionField;
        
        private string organizacionField;
        
        private string cargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AcuerdoInfoTypeGrupoParticipanteEstado Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object Observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        ///No viene  por defecto en el archivo XSD
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Celular
        {
            get
            {
                return this.celularField;
            }
            set
            {
                this.celularField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("FechaEnvioParaFirma")]
        public string FechaEnvioParaFirmaString
        {
            get
            {
                return this.fechaEnvioParaFirmaField.HasValue ? XmlConvert.ToString(fechaEnvioParaFirmaField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaEnvioParaFirmaField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTime? FechaEnvioParaFirma
        {
            get
            {
                return this.fechaEnvioParaFirmaField;
            }
            set
            {
                this.fechaEnvioParaFirmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaEnvioParaFirmaSpecified
        {
            get
            {
                return this.fechaEnvioParaFirmaFieldSpecified;
            }
            set
            {
                this.fechaEnvioParaFirmaFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("FechaLecturaParaFirma")]
        public string FechaLecturaParaFirmaString
        {
            get
            {
                return this.fechaLecturaParaFirmaField.HasValue ? XmlConvert.ToString(fechaLecturaParaFirmaField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaLecturaParaFirmaField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTime? FechaLecturaParaFirma
        {
            get
            {
                return this.fechaLecturaParaFirmaField;
            }
            set
            {
                this.fechaLecturaParaFirmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaLecturaParaFirmaSpecified
        {
            get
            {
                return this.fechaLecturaParaFirmaFieldSpecified;
            }
            set
            {
                this.fechaLecturaParaFirmaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IpLecturaParaFirma
        {
            get
            {
                return this.ipLecturaParaFirmaField;
            }
            set
            {
                this.ipLecturaParaFirmaField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("FechaRespuesta")]
        public string FechaRespuestaString
        {
            get
            {
                return this.fechaRespuestaField.HasValue ? XmlConvert.ToString(fechaRespuestaField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaRespuestaField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTime? FechaRespuesta
        {
            get
            {
                return this.fechaRespuestaField;
            }
            set
            {
                this.fechaRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaRespuestaSpecified
        {
            get
            {
                return this.fechaRespuestaFieldSpecified;
            }
            set
            {
                this.fechaRespuestaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IpRespuesta
        {
            get
            {
                return this.ipRespuestaField;
            }
            set
            {
                this.ipRespuestaField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("FechaEnvioDocumentoFirmado")]
        public string FechaEnvioDocumentoFirmadoString
        {
            get
            {
                return this.fechaEnvioDocumentoFirmadoField.HasValue ? XmlConvert.ToString(fechaEnvioDocumentoFirmadoField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaEnvioDocumentoFirmadoField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTime? FechaEnvioDocumentoFirmado
        {
            get
            {
                return this.fechaEnvioDocumentoFirmadoField;
            }
            set
            {
                this.fechaEnvioDocumentoFirmadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaEnvioDocumentoFirmadoSpecified
        {
            get
            {
                return this.fechaEnvioDocumentoFirmadoFieldSpecified;
            }
            set
            {
                this.fechaEnvioDocumentoFirmadoFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("FechaDescargaDocumentoFirmado")]
        public string FechaDescargaDocumentoFirmadoString
        {
            get
            {
                return this.fechaDescargaDocumentoFirmadoField.HasValue ? XmlConvert.ToString(fechaDescargaDocumentoFirmadoField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaDescargaDocumentoFirmadoField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTime? FechaDescargaDocumentoFirmado
        {
            get
            {
                return this.fechaDescargaDocumentoFirmadoField;
            }
            set
            {
                this.fechaDescargaDocumentoFirmadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaDescargaDocumentoFirmadoSpecified
        {
            get
            {
                return this.fechaDescargaDocumentoFirmadoFieldSpecified;
            }
            set
            {
                this.fechaDescargaDocumentoFirmadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IpDescargaDocumentoFirmado
        {
            get
            {
                return this.ipDescargaDocumentoFirmadoField;
            }
            set
            {
                this.ipDescargaDocumentoFirmadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NombreEnFirma
        {
            get
            {
                return this.nombreEnFirmaField;
            }
            set
            {
                this.nombreEnFirmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Organizacion
        {
            get
            {
                return this.organizacionField;
            }
            set
            {
                this.organizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cargo
        {
            get
            {
                return this.cargoField;
            }
            set
            {
                this.cargoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
  //  [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoTypeGrupoParticipanteEstado
    {
        
        private string idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public enum AcuerdoInfoTypeGrupoRol
    {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoTypeDocumento
    {
        
        private string idField;
        
        private string naturalezaField;
        
        private string nombreField;
        
        private int ordenField;
        
        private System.DateTime? fechaCargaField;
        
        private bool fechaCargaFieldSpecified;
        
        private string usuarioCargaField;
        
        private string aplicacionCargaField;
        
        private bool eliminadoField;
        
        private bool eliminadoFieldSpecified;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Naturaleza
        {
            get
            {
                return this.naturalezaField;
            }
            set
            {
                this.naturalezaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("FechaCarga")]
        public string FechaCargaString
        {
            get
            {
                return this.fechaCargaField.HasValue ? XmlConvert.ToString(fechaCargaField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaCargaField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTime? FechaCarga
        {
            get
            {
                return this.fechaCargaField;
            }
            set
            {
                this.fechaCargaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaCargaSpecified
        {
            get
            {
                return this.fechaCargaFieldSpecified;
            }
            set
            {
                this.fechaCargaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UsuarioCarga
        {
            get
            {
                return this.usuarioCargaField;
            }
            set
            {
                this.usuarioCargaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AplicacionCarga
        {
            get
            {
                return this.aplicacionCargaField;
            }
            set
            {
                this.aplicacionCargaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Eliminado
        {
            get
            {
                return this.eliminadoField;
            }
            set
            {
                this.eliminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EliminadoSpecified
        {
            get
            {
                return this.eliminadoFieldSpecified;
            }
            set
            {
                this.eliminadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoTypeCopias
    {
        
        private AcuerdoInfoTypeCopiasParticipante participanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AcuerdoInfoTypeCopiasParticipante Participante
        {
            get
            {
                return this.participanteField;
            }
            set
            {
                this.participanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfoTypeCopiasParticipante
    {
        
        private string emailField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public enum AcuerdoInfoTypeSegundoFacAut
    {
        
        /// <remarks/>
        OTP
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public enum AcuerdoTypeGrupoRol
    {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoTypeCopia
    {
        
        private string emailField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoTypeDocumento
    {
        
        private string nombreField;
        
        private AcuerdoTypeDocumentoTipoMime tipoMimeField;
        
        private AcuerdoTypeDocumentoCodificacion codificacionField;
        
        private string valueField;
        
        public AcuerdoTypeDocumento()
        {
           // this.tipoMimeField = AcuerdoTypeDocumentoTipoMime.applicationpdf;
            this.codificacionField = AcuerdoTypeDocumentoCodificacion.Base64;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        //[System.ComponentModel.DefaultValueAttribute(AcuerdoTypeDocumentoTipoMime.applicationpdf)]
        public AcuerdoTypeDocumentoTipoMime TipoMime
        {
            get
            {
                return this.tipoMimeField;
            }
            set
            {
                this.tipoMimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AcuerdoTypeDocumentoCodificacion.Base64)]
        public AcuerdoTypeDocumentoCodificacion Codificacion
        {
            get
            {
                return this.codificacionField;
            }
            set
            {
                this.codificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public enum AcuerdoTypeDocumentoTipoMime
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/pdf")]
        applicationpdf,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application_vnd.ms/excel")]
        application_vndmsexcel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.openxmlformats-officedocument.spreadsheetml.template")]
        applicationvndopenxmlformatsofficedocumentspreadsheetmltemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-excel.sheet.macroEnabled.12")]
        applicationvndmsexcelsheetmacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-excel.template.macroEnabled.12")]
        applicationvndmsexceltemplatemacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-excel.addin.macroEnabled.12")]
        applicationvndmsexceladdinmacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-excel.sheet.binary.macroEnabled.12")]
        applicationvndmsexcelsheetbinarymacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("text/html")]
        texthtml,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("image/pjpeg")]
        imagepjpeg,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/octet-stream")]
        applicationoctetstream,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("text/plain")]
        textplain,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/msword")]
        applicationmsword,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/msword")]
        applicationmsword1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("image/gif")]
        imagegif,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("text/xml")]
        textxml,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("image/x-png")]
        imagexpng,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("image/png")]
        imagepng,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-powerpoint")]
        applicationvndmspowerpoint,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.openxmlformats-officedocument.presentationml.presentation")]
        applicationvndopenxmlformatsofficedocumentpresentationmlpresentation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.openxmlformats-officedocument.presentationml.template")]
        applicationvndopenxmlformatsofficedocumentpresentationmltemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.openxmlformats-officedocument.presentationml.slideshow")]
        applicationvndopenxmlformatsofficedocumentpresentationmlslideshow,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-powerpoint.addin.macroEnabled.12")]
        applicationvndmspowerpointaddinmacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-powerpoint.presentation.macroEnabled.12")]
        applicationvndmspowerpointpresentationmacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-powerpoint.template.macroEnabled.12")]
        applicationvndmspowerpointtemplatemacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-powerpoint.slideshow.macroEnabled.12")]
        applicationvndmspowerpointslideshowmacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("image/tiff")]
        imagetiff,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("image/jpeg")]
        imagejpeg,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.openxmlformats_xlsx")]
        applicationvndopenxmlformats_xlsx,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.openxmlformats")]
        applicationvndopenxmlformats,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.openxmlformats-officedocument.wordprocessingml.template")]
        applicationvndopenxmlformatsofficedocumentwordprocessingmltemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-word.document.macroEnabled.12")]
        applicationvndmsworddocumentmacroEnabled12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.ms-word.document.macroEnabled.12")]
        applicationvndmsworddocumentmacroEnabled121,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("text/csv")]
        textcsv,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.oasis.opendocument.text")]
        applicationvndoasisopendocumenttext,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/rtf")]
        applicationrtf,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.oasis.opendocument.presentation")]
        applicationvndoasisopendocumentpresentation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/vnd.oasis.opendocument.spreadsheet")]
        applicationvndoasisopendocumentspreadsheet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public enum AcuerdoTypeDocumentoCodificacion
    {
        
        /// <remarks/>
        Base64,
        
        /// <remarks/>
        IdDocAZSign,
        
        /// <remarks/>
        Path,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoTypeRemitente
    {
        
        private string idRemitenteField;
        
        private string nombreField;
        
        private string emailField;
        
        private string organizacionField;
        
        private string dependenciaField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdRemitente
        {
            get
            {
                return this.idRemitenteField;
            }
            set
            {
                this.idRemitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Organizacion
        {
            get
            {
                return this.organizacionField;
            }
            set
            {
                this.organizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Dependencia
        {
            get
            {
                return this.dependenciaField;
            }
            set
            {
                this.dependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public enum AcuerdoTypeTipoFirma
    {
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        D,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public enum AcuerdoTypeEstado
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1-P")]
        Item1P,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2-T")]
        Item2T,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public enum AcuerdoTypeSegundoFacAut
    {
        
        /// <remarks/>
        OTP,
        
        /// <remarks/>
        VTU,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.analitica.com.co/AZSign/Esquemas")]
    [XmlRoot(Namespace = "http://www.analitica.com.co/AZSign/Esquemas", ElementName = "AcuerdoRsp")]
    public partial class AcuerdoRsp
    {

        //[XmlNamespaceDeclarations]
        //public XmlSerializerNamespaces xmlns = new XmlSerializerNamespaces(new[] {
        //    new XmlQualifiedName("azs", "http://www.analitica.com.co/AZSign/Esquemas")
        //});

        private AcuerdoRspDocumentos[] documentosField;
        
        private string cuentaField;
        
        private string aplicacionField;
        
        private string acuerdoIdField;
        
        private string acuerdoNombreField;
        
        private System.DateTime? fechaHoraField;
        
        private string vencimientoField;
        
        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Documento", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public AcuerdoRspDocumentos[] Documentos
        {
            get
            {
                return this.documentosField;
            }
            set
            {
                this.documentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cuenta
        {
            get
            {
                return this.cuentaField;
            }
            set
            {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Aplicacion
        {
            get
            {
                return this.aplicacionField;
            }
            set
            {
                this.aplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AcuerdoId
        {
            get
            {
                return this.acuerdoIdField;
            }
            set
            {
                this.acuerdoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AcuerdoNombre
        {
            get
            {
                return this.acuerdoNombreField;
            }
            set
            {
                this.acuerdoNombreField = value;
            }
        }


        [System.Xml.Serialization.XmlAttributeAttribute("FechaHora")]
        public string FechaHoraString
        {
            get
            {
                return this.fechaHoraField.HasValue ? XmlConvert.ToString(fechaHoraField.Value, XmlDateTimeSerializationMode.Unspecified)
                : string.Empty;
            }
            set
            {
                this.fechaHoraField = !string.IsNullOrEmpty(value) ? XmlConvert.ToDateTime(Utility.ConvertirFechaToW3C(value), XmlDateTimeSerializationMode.Unspecified) : (System.DateTime?)null;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public System.DateTime? FechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vencimiento
        {
            get
            {
                return this.vencimientoField;
            }
            set
            {
                this.vencimientoField = value;
            }
        }
    }
    
   // /// <remarks/>
   // [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
   //// [System.Diagnostics.DebuggerStepThroughAttribute()]
   // [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
   // public partial class AcuerdoRspDocumentos
   // {
        
   //     private AcuerdoRspDocumentosDocumento documentoField;

   //     /// <remarks/>
   //     [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
   //     public AcuerdoRspDocumentosDocumento Documento
   //     {
   //         get
   //         {
   //             return this.documentoField;
   //         }
   //         set
   //         {
   //             this.documentoField = value;
   //         }
   //     }
   // }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoRspDocumentos
    {
        
        private string idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcuerdoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas", Order=0)]
        public ServiceReference2.Acuerdo Acuerdo;
        
        public AcuerdoRequest()
        {
        }
        
        public AcuerdoRequest(ServiceReference2.Acuerdo Acuerdo)
        {
            this.Acuerdo = Acuerdo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.analitica.com.co/AZSign/Esquemas")]
    [XmlRoot(Namespace = "http://www.analitica.com.co/AZSign/Esquemas", ElementName = "AcuerdoRsp")]
    public partial class AcuerdoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas", Order=0)]
        [XmlNamespaceDeclarations]
        public XmlSerializerNamespaces xmlns = new XmlSerializerNamespaces(new[] {
            new XmlQualifiedName("azs", "http://www.analitica.com.co/AZSign/Esquemas")
        });
        public ServiceReference2.AcuerdoRsp AcuerdoRsp;
        
        public AcuerdoResponse()
        {
        }
        
        public AcuerdoResponse(ServiceReference2.AcuerdoRsp AcuerdoRsp)
        {
            this.AcuerdoRsp = AcuerdoRsp;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    [XmlRoot(Namespace = "http://www.analitica.com.co/AZSign/Esquemas", ElementName = "SolicitarAcuerdoInfo")]
    public partial class SolicitarAcuerdoInfo
    {

        [XmlNamespaceDeclarations]
        public XmlSerializerNamespaces xmlns = new XmlSerializerNamespaces(new[] {
            new XmlQualifiedName("azs", "http://www.analitica.com.co/AZSign/Esquemas")
        });

        private string cuentaField;
        
        private string aplicativoField;
        
        private string acuerdoIdField;
        
        private bool incluirDocsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cuenta
        {
            get
            {
                return this.cuentaField;
            }
            set
            {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Aplicativo
        {
            get
            {
                return this.aplicativoField;
            }
            set
            {
                this.aplicativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AcuerdoId
        {
            get
            {
                return this.acuerdoIdField;
            }
            set
            {
                this.acuerdoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IncluirDocs
        {
            get
            {
                return this.incluirDocsField;
            }
            set
            {
                this.incluirDocsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.analitica.com.co/AZSign/Esquemas")]
    public partial class AcuerdoInfo : AcuerdoInfoType
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarInfoAcuerdoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas", Order=0)]
        public ServiceReference2.SolicitarAcuerdoInfo SolicitarAcuerdoInfo;
        
        public SolicitarInfoAcuerdoRequest()
        {
        }
        
        public SolicitarInfoAcuerdoRequest(ServiceReference2.SolicitarAcuerdoInfo SolicitarAcuerdoInfo)
        {
            this.SolicitarAcuerdoInfo = SolicitarAcuerdoInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitarInfoAcuerdoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.analitica.com.co/AZSign/Esquemas", Order=0)]
        public ServiceReference2.AcuerdoInfo AcuerdoInfo;
        
        public SolicitarInfoAcuerdoResponse()
        {
        }
        
        public SolicitarInfoAcuerdoResponse(ServiceReference2.AcuerdoInfo AcuerdoInfo)
        {
            this.AcuerdoInfo = AcuerdoInfo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServiciosAZSign_SOAPChannel : ServiceReference2.ServiciosAZSign_SOAP, System.ServiceModel.IClientChannel
    {
    }
    
   // [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiciosAZSign_SOAPClient : System.ServiceModel.ClientBase<ServiceReference2.ServiciosAZSign_SOAP>, ServiceReference2.ServiciosAZSign_SOAP
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiciosAZSign_SOAPClient() : 
                base(ServiciosAZSign_SOAPClient.GetDefaultBinding(), ServiciosAZSign_SOAPClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServiciosAZSign_SOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosAZSign_SOAPClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiciosAZSign_SOAPClient.GetBindingForEndpoint(endpointConfiguration), ServiciosAZSign_SOAPClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosAZSign_SOAPClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiciosAZSign_SOAPClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosAZSign_SOAPClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiciosAZSign_SOAPClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosAZSign_SOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.AcuerdoResponse> ServiceReference2.ServiciosAZSign_SOAP.AcuerdoAsync(ServiceReference2.AcuerdoRequest request)
        {
            return base.Channel.AcuerdoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.AcuerdoResponse> AcuerdoAsync(ServiceReference2.Acuerdo Acuerdo)
        {
            ServiceReference2.AcuerdoRequest inValue = new ServiceReference2.AcuerdoRequest();
            inValue.Acuerdo = Acuerdo;
            return ((ServiceReference2.ServiciosAZSign_SOAP)(this)).AcuerdoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.SolicitarInfoAcuerdoResponse> ServiceReference2.ServiciosAZSign_SOAP.SolicitarInfoAcuerdoAsync(ServiceReference2.SolicitarInfoAcuerdoRequest request)
        {
            return base.Channel.SolicitarInfoAcuerdoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.SolicitarInfoAcuerdoResponse> SolicitarInfoAcuerdoAsync(ServiceReference2.SolicitarAcuerdoInfo SolicitarAcuerdoInfo)
        {
            ServiceReference2.SolicitarInfoAcuerdoRequest inValue = new ServiceReference2.SolicitarInfoAcuerdoRequest();
            inValue.SolicitarAcuerdoInfo = SolicitarAcuerdoInfo;
            return ((ServiceReference2.ServiciosAZSign_SOAP)(this)).SolicitarInfoAcuerdoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiciosAZSign_SOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();

                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;

                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;

                //result.Security.Transport.ProxyCredentialType = System.ServiceModel.HttpProxyCredentialType.None;
                //result.Security.Message.ClientCredentialType = System.ServiceModel.BasicHttpMessageCredentialType.UserName;
                ///

                //System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();

                //result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                //result.MaxReceivedMessageSize = int.MaxValue;
                //result.AllowCookies = true;
                //result.Security.Mode = System.ServiceModel.SecurityMode.Transport;

                //result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                ////result.Security.Transport.ProxyCredentialType = System.ServiceModel.HttpProxyCredentialType.None;
                //result.Security.Message.ClientCredentialType = System.ServiceModel.MessageCredentialType.None;

                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiciosAZSign_SOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://azsign.analitica.com.co/WebServices/SOAP/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiciosAZSign_SOAPClient.GetBindingForEndpoint(EndpointConfiguration.ServiciosAZSign_SOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiciosAZSign_SOAPClient.GetEndpointAddress(EndpointConfiguration.ServiciosAZSign_SOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            ServiciosAZSign_SOAP,
        }
    }

    public static class Utility
    {
        public static string ConvertirFechaToW3C(string fechaOriginal)
        {
            DateTime fechaDateTime = DateTime.ParseExact(fechaOriginal, "yyyy-MM-dd HH:mm:ss", null);

            // Convertirla al formato W3C XML Schema (ISO 8601) utilizando la cadena "o"
            string fechaW3C = fechaDateTime.ToString("o");
            return fechaW3C;
        }
    }
}
